#!/usr/bin/env python
import os
import sys
import MDAnalysis as mda


def main():
    if len(sys.argv[1:])!=3:
        print("Usage: python %s <xtcf> <topf> <outp>"%sys.argv[0])
        sys.exit(0)
    xtcf,topf,outp = sys.argv[1:]
    if not os.path.exists(outp):
        os.mkdir(outp)
    u = mda.Universe(topf, xtcf)
    i = 0
    for ts in u.trajectory:
        protein = u.select_atoms("all")
        protein.write(os.path.join(outp,"c%d.pdb"%i))
        i+=1

if __name__ == "__main__":
    main()

